//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.View.Plugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.View.Plugins.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin you try to show is deactivated..
        /// </summary>
        internal static string Ex_DeactivatedPluginException {
            get {
                return ResourceManager.GetString("Ex_DeactivatedPluginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration of the runtime context of nDoctor is invalid.
        /// </summary>
        internal static string Ex_NDoctorConfigurationException {
            get {
                return ResourceManager.GetString("Ex_NDoctorConfigurationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin validator is not set. Please configure a validator for all the plugins.
        /// </summary>
        internal static string Ex_NullPluginValidatorException {
            get {
                return ResourceManager.GetString("Ex_NullPluginValidatorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration of the plugins is incorrect. Maybe the configuration files are badly written..
        /// </summary>
        internal static string Ex_PluginConfigurationException {
            get {
                return ResourceManager.GetString("Ex_PluginConfigurationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured in a plugins..
        /// </summary>
        internal static string Ex_PluginException {
            get {
                return ResourceManager.GetString("Ex_PluginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin doesn&apos;t have validation rules..
        /// </summary>
        internal static string Ex_PluginException_NoValidator {
            get {
                return ResourceManager.GetString("Ex_PluginException_NoValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one plugin that override the default start page are loaded. Only one can be activated..
        /// </summary>
        internal static string Ex_PluginException_SeveralStartPages {
            get {
                return ResourceManager.GetString("Ex_PluginException_SeveralStartPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory of the plugin &apos;{0}&apos; doesn&apos;t exist.
        ///Path: {1}.
        /// </summary>
        internal static string Ex_PluginNotFoundException {
            get {
                return ResourceManager.GetString("Ex_PluginNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugins aren&apos;t loaded in memory. Please execute the plugin loader before..
        /// </summary>
        internal static string Ex_PluginNotLoadedException {
            get {
                return ResourceManager.GetString("Ex_PluginNotLoadedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data context of the item is not at the expected type..
        /// </summary>
        internal static string Ex_WrongDataContextException {
            get {
                return ResourceManager.GetString("Ex_WrongDataContextException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not granted to execute this feature.
        /// </summary>
        internal static string Msg_ErrorAuthorisation {
            get {
                return ResourceManager.GetString("Msg_ErrorAuthorisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers.
        /// </summary>
        internal static string Msg_GroupManager {
            get {
                return ResourceManager.GetString("Msg_GroupManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is not set in the configuration file. Please set it up..
        /// </summary>
        internal static string Msg_MissingParameterInConfiguration {
            get {
                return ResourceManager.GetString("Msg_MissingParameterInConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration manager.
        /// </summary>
        internal static string Plugin_Administration {
            get {
                return ResourceManager.GetString("Plugin_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to manage all the data not directly related to the patient.
        /// </summary>
        internal static string Plugin_Administration_Explanations {
            get {
                return ResourceManager.GetString("Plugin_Administration_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorisation manager.
        /// </summary>
        internal static string Plugin_Authorisation {
            get {
                return ResourceManager.GetString("Plugin_Authorisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to manage authorisations of the modules of nDoctor.
        /// </summary>
        internal static string Plugin_Authorisation_Explanations {
            get {
                return ResourceManager.GetString("Plugin_Authorisation_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI history manager.
        /// </summary>
        internal static string Plugin_Bmi {
            get {
                return ResourceManager.GetString("Plugin_Bmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to manage the BMI history of a patient.
        /// </summary>
        internal static string Plugin_Bmi_Explanations {
            get {
                return ResourceManager.GetString("Plugin_Bmi_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data importer.
        /// </summary>
        internal static string Plugin_DbImport {
            get {
                return ResourceManager.GetString("Plugin_DbImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to import data from a Sharpenda database.
        /// </summary>
        internal static string Plugin_DbImport_Explanations {
            get {
                return ResourceManager.GetString("Plugin_DbImport_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family manager.
        /// </summary>
        internal static string Plugin_FamilyManager {
            get {
                return ResourceManager.GetString("Plugin_FamilyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to manage the family of a patient.
        /// </summary>
        internal static string Plugin_FamilyManager_Explanations {
            get {
                return ResourceManager.GetString("Plugin_FamilyManager_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical record manager.
        /// </summary>
        internal static string Plugin_MedicalRecordManager {
            get {
                return ResourceManager.GetString("Plugin_MedicalRecordManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to manage the medical records of a patient.
        /// </summary>
        internal static string Plugin_MedicalRecordManager_Explanations {
            get {
                return ResourceManager.GetString("Plugin_MedicalRecordManager_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Plugin_MeetingManager {
            get {
                return ResourceManager.GetString("Plugin_MeetingManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to manage the appointments with patients.
        /// </summary>
        internal static string Plugin_MeetingManager_Explanations {
            get {
                return ResourceManager.GetString("Plugin_MeetingManager_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathology manager.
        /// </summary>
        internal static string Plugin_PathologyManager {
            get {
                return ResourceManager.GetString("Plugin_PathologyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to manage the pathology history of a patient.
        /// </summary>
        internal static string Plugin_PathologyManager_Explanations {
            get {
                return ResourceManager.GetString("Plugin_PathologyManager_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient data manager (Old version).
        /// </summary>
        internal static string Plugin_PatientDataManager {
            get {
                return ResourceManager.GetString("Plugin_PatientDataManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to manage the data of a patient.
        /// </summary>
        internal static string Plugin_PatientDataManager_Explanations {
            get {
                return ResourceManager.GetString("Plugin_PatientDataManager_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionnaire de données patient.
        /// </summary>
        internal static string Plugin_PatientDataManager2 {
            get {
                return ResourceManager.GetString("Plugin_PatientDataManager2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient session manager.
        /// </summary>
        internal static string Plugin_PatientSessionManager {
            get {
                return ResourceManager.GetString("Plugin_PatientSessionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to manage a patient sessions. Has tools to search and to load a patient.
        /// </summary>
        internal static string Plugin_PatientSessionManager_Explanations {
            get {
                return ResourceManager.GetString("Plugin_PatientSessionManager_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical pictures manager.
        /// </summary>
        internal static string Plugin_PictureManager {
            get {
                return ResourceManager.GetString("Plugin_PictureManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to manage medical pictures of a patient.
        /// </summary>
        internal static string Plugin_PictureManager_Explanations {
            get {
                return ResourceManager.GetString("Plugin_PictureManager_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescriptions manager.
        /// </summary>
        internal static string Plugin_PrescriptionManager {
            get {
                return ResourceManager.GetString("Plugin_PrescriptionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to manage the prescriptions of a patient.
        /// </summary>
        internal static string Plugin_PrescriptionManager_Explanations {
            get {
                return ResourceManager.GetString("Plugin_PrescriptionManager_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescue tools for the database.
        /// </summary>
        internal static string Plugin_RescueTools {
            get {
                return ResourceManager.GetString("Plugin_RescueTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides rescue tools to manage inconsistencies in the database.
        /// </summary>
        internal static string Plugin_RescueTools_Explanations {
            get {
                return ResourceManager.GetString("Plugin_RescueTools_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User session manager.
        /// </summary>
        internal static string Plugin_UserSessionManager {
            get {
                return ResourceManager.GetString("Plugin_UserSessionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to manage the user sessions.
        /// </summary>
        internal static string Plugin_UserSessionManager_Explanations {
            get {
                return ResourceManager.GetString("Plugin_UserSessionManager_Explanations", resourceCulture);
            }
        }
    }
}
