//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Domain.DTO.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Domain.DTO.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start time should be smaller than the end time.
        /// </summary>
        internal static string Error_BeginBiggerThanEnd {
            get {
                return ResourceManager.GetString("Error_BeginBiggerThanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of hours has to be between 0 and 23.
        /// </summary>
        internal static string Error_NotSupportedDate_Hour {
            get {
                return ResourceManager.GetString("Error_NotSupportedDate_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of minutes has to be between 0 and 59.
        /// </summary>
        internal static string Error_NotSupportedDate_Minutes {
            get {
                return ResourceManager.GetString("Error_NotSupportedDate_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program seems to be in an infinite loop.
        /// </summary>
        internal static string Error_TooManyLoops {
            get {
                return ResourceManager.GetString("Error_TooManyLoops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to convert &quot;{0}&quot; into time.
        /// </summary>
        internal static string Error_WrongTextForDate {
            get {
                return ResourceManager.GetString("Error_WrongTextForDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        internal static string TagType_Appointment {
            get {
                return ResourceManager.GetString("TagType_Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son.
        /// </summary>
        internal static string TagType_Child {
            get {
                return ResourceManager.GetString("TagType_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string TagType_Doctor {
            get {
                return ResourceManager.GetString("TagType_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug.
        /// </summary>
        internal static string TagType_Drug {
            get {
                return ResourceManager.GetString("TagType_Drug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical record.
        /// </summary>
        internal static string TagType_MedicalRecord {
            get {
                return ResourceManager.GetString("TagType_MedicalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string TagType_Parent {
            get {
                return ResourceManager.GetString("TagType_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathology.
        /// </summary>
        internal static string TagType_Pathology {
            get {
                return ResourceManager.GetString("TagType_Pathology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string TagType_Patient {
            get {
                return ResourceManager.GetString("TagType_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string TagType_Picture {
            get {
                return ResourceManager.GetString("TagType_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription.
        /// </summary>
        internal static string TagType_Prescription {
            get {
                return ResourceManager.GetString("TagType_Prescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription document.
        /// </summary>
        internal static string TagType_PrescriptionDocument {
            get {
                return ResourceManager.GetString("TagType_PrescriptionDocument", resourceCulture);
            }
        }
    }
}
