//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.View.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.View.Core.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log directory.
        /// </summary>
        internal static string Btn_OpenLogs {
            get {
                return ResourceManager.GetString("Btn_OpenLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to nDoctor web site....
        /// </summary>
        internal static string Btn_OpenSite {
            get {
                return ResourceManager.GetString("Btn_OpenSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Read logs for further information..
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not granted to executie this feature.
        /// </summary>
        internal static string Error_UnauthorisedAction {
            get {
                return ResourceManager.GetString("Error_UnauthorisedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin host is not configured. Check the state of the plugin context..
        /// </summary>
        internal static string Ex_NDoctorConfigurationException_HostNull {
            get {
                return ResourceManager.GetString("Ex_NDoctorConfigurationException_HostNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start page was already configured by a plugin..
        /// </summary>
        internal static string Ex_PluginException_StartPageAlreadySet {
            get {
                return ResourceManager.GetString("Ex_PluginException_StartPageAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_Englisg {
            get {
                return ResourceManager.GetString("Language_Englisg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string Language_French {
            get {
                return ResourceManager.GetString("Language_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start page.
        /// </summary>
        internal static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load this patient.
        /// </summary>
        internal static string Menu_Select {
            get {
                return ResourceManager.GetString("Menu_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to quit the application?.
        /// </summary>
        internal static string Msg_AskForShutdown {
            get {
                return ResourceManager.GetString("Msg_AskForShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring config file....
        /// </summary>
        internal static string Msg_ConfiguringConfigFile {
            get {
                return ResourceManager.GetString("Msg_ConfiguringConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring nHibernate....
        /// </summary>
        internal static string Msg_ConfiguringNHibernate {
            get {
                return ResourceManager.GetString("Msg_ConfiguringNHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring plugins....
        /// </summary>
        internal static string Msg_ConfiguringPlugins {
            get {
                return ResourceManager.GetString("Msg_ConfiguringPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring Status Writer....
        /// </summary>
        internal static string Msg_ConfiguringStatusWriter {
            get {
                return ResourceManager.GetString("Msg_ConfiguringStatusWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring StructureMap....
        /// </summary>
        internal static string Msg_ConfiguringStructureMap {
            get {
                return ResourceManager.GetString("Msg_ConfiguringStructureMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails creation....
        /// </summary>
        internal static string Msg_ConfiguringThumbnails {
            get {
                return ResourceManager.GetString("Msg_ConfiguringThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring window manager....
        /// </summary>
        internal static string Msg_ConfiguringViewService {
            get {
                return ResourceManager.GetString("Msg_ConfiguringViewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient: {0}.
        /// </summary>
        internal static string Msg_ConnectedPatient {
            get {
                return ResourceManager.GetString("Msg_ConnectedPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path specified for the database is incorrect..
        /// </summary>
        internal static string Msg_ErrorDatabaseNotFound {
            get {
                return ResourceManager.GetString("Msg_ErrorDatabaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. {0}.
        /// </summary>
        internal static string Msg_ErrorOccured {
            get {
                return ResourceManager.GetString("Msg_ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///The application will close. Check the logs for further  information.
        /// </summary>
        internal static string Msg_FatalErrorOccured {
            get {
                return ResourceManager.GetString("Msg_FatalErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Msg_Loading {
            get {
                return ResourceManager.GetString("Msg_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart nDoctor to apply changes!.
        /// </summary>
        internal static string Msg_NeedRestart {
            get {
                return ResourceManager.GetString("Msg_NeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody.
        /// </summary>
        internal static string Msg_Nobody {
            get {
                return ResourceManager.GetString("Msg_Nobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: {0,3}%.
        /// </summary>
        internal static string Msg_Progess {
            get {
                return ResourceManager.GetString("Msg_Progess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string Msg_Ready {
            get {
                return ResourceManager.GetString("Msg_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafraîchissement des statistiques....
        /// </summary>
        internal static string Msg_RefreshingStat {
            get {
                return ResourceManager.GetString("Msg_RefreshingStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open record of {0}.
        /// </summary>
        internal static string Msg_SelectPatient {
            get {
                return ResourceManager.GetString("Msg_SelectPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning. {0}.
        /// </summary>
        internal static string Msg_WarningOccured {
            get {
                return ResourceManager.GetString("Msg_WarningOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main menu of the application does&apos;t exist..
        /// </summary>
        internal static string PluginException_HomeMenuVoid {
            get {
                return ResourceManager.GetString("PluginException_HomeMenuVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        internal static string SlotDuration_OneHour {
            get {
                return ResourceManager.GetString("SlotDuration_OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        internal static string SlotDuration_ThirtyMinutes {
            get {
                return ResourceManager.GetString("SlotDuration_ThirtyMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About nDoctor.
        /// </summary>
        internal static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        internal static string Title_Address {
            get {
                return ResourceManager.GetString("Title_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically display contextual menus.
        /// </summary>
        internal static string Title_AutomaticShowContext {
            get {
                return ResourceManager.GetString("Title_AutomaticShowContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average execution time (msec).
        /// </summary>
        internal static string Title_AverageExecutionTime {
            get {
                return ResourceManager.GetString("Title_AverageExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average usage of components.
        /// </summary>
        internal static string Title_AverageUse {
            get {
                return ResourceManager.GetString("Title_AverageUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average execution time (sec).
        /// </summary>
        internal static string Title_AvgExecutionTime {
            get {
                return ResourceManager.GetString("Title_AvgExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average threshold (sec).
        /// </summary>
        internal static string Title_AvgThreshold {
            get {
                return ResourceManager.GetString("Title_AvgThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottlenecks.
        /// </summary>
        internal static string Title_Bottlenecks {
            get {
                return ResourceManager.GetString("Title_Bottlenecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box:.
        /// </summary>
        internal static string Title_Box {
            get {
                return ResourceManager.GetString("Title_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string Title_City {
            get {
                return ResourceManager.GetString("Title_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Title_Contact {
            get {
                return ResourceManager.GetString("Title_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact data.
        /// </summary>
        internal static string Title_ContactData {
            get {
                return ResourceManager.GetString("Title_ContactData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Title_Count {
            get {
                return ResourceManager.GetString("Title_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string Title_Data {
            get {
                return ResourceManager.GetString("Title_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string Title_DefaultSettings {
            get {
                return ResourceManager.GetString("Title_DefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string Title_End {
            get {
                return ResourceManager.GetString("Title_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error.
        /// </summary>
        internal static string Title_Fatal {
            get {
                return ResourceManager.GetString("Title_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        internal static string Title_FirstName {
            get {
                return ResourceManager.GetString("Title_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        internal static string Title_Gender {
            get {
                return ResourceManager.GetString("Title_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string Title_GlobalTools {
            get {
                return ResourceManager.GetString("Title_GlobalTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Title_Interogation {
            get {
                return ResourceManager.GetString("Title_Interogation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Title_Languages {
            get {
                return ResourceManager.GetString("Title_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        internal static string Title_LastName {
            get {
                return ResourceManager.GetString("Title_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string Title_Managers {
            get {
                return ResourceManager.GetString("Title_Managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Title_Method {
            get {
                return ResourceManager.GetString("Title_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divers.
        /// </summary>
        internal static string Title_Miscellaneous {
            get {
                return ResourceManager.GetString("Title_Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom:.
        /// </summary>
        internal static string Title_Name {
            get {
                return ResourceManager.GetString("Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string Title_Notes {
            get {
                return ResourceManager.GetString("Title_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nDoctor 3 .
        /// </summary>
        internal static string Title_NoUserConnected {
            get {
                return ResourceManager.GetString("Title_NoUserConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private data.
        /// </summary>
        internal static string Title_PersonalData {
            get {
                return ResourceManager.GetString("Title_PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tél.:.
        /// </summary>
        internal static string Title_Phone {
            get {
                return ResourceManager.GetString("Title_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed plugins:.
        /// </summary>
        internal static string Title_Plugins {
            get {
                return ResourceManager.GetString("Title_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code:.
        /// </summary>
        internal static string Title_PostalCode {
            get {
                return ResourceManager.GetString("Title_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail:.
        /// </summary>
        internal static string Title_ProMail {
            get {
                return ResourceManager.GetString("Title_ProMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile:.
        /// </summary>
        internal static string Title_ProMobile {
            get {
                return ResourceManager.GetString("Title_ProMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string Title_ProPhone {
            get {
                return ResourceManager.GetString("Title_ProPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient: {0}.
        /// </summary>
        internal static string Title_SelectedPatient {
            get {
                return ResourceManager.GetString("Title_SelectedPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nDoctor 3 - Connecté en tant que {0}.
        /// </summary>
        internal static string Title_SelectedUser {
            get {
                return ResourceManager.GetString("Title_SelectedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string Title_SessionManagers {
            get {
                return ResourceManager.GetString("Title_SessionManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customise.
        /// </summary>
        internal static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot duration.
        /// </summary>
        internal static string Title_SlotDuration {
            get {
                return ResourceManager.GetString("Title_SlotDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialisation:.
        /// </summary>
        internal static string Title_Specialisation {
            get {
                return ResourceManager.GetString("Title_Specialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Title_Start {
            get {
                return ResourceManager.GetString("Title_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        internal static string Title_Street {
            get {
                return ResourceManager.GetString("Title_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr:.
        /// </summary>
        internal static string Title_StreetNr {
            get {
                return ResourceManager.GetString("Title_StreetNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        internal static string Title_TargetType {
            get {
                return ResourceManager.GetString("Title_TargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Title_Tools {
            get {
                return ResourceManager.GetString("Title_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workday.
        /// </summary>
        internal static string Title_Workday {
            get {
                return ResourceManager.GetString("Title_Workday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written by {0}.
        /// </summary>
        internal static string Title_WrittenBy {
            get {
                return ResourceManager.GetString("Title_WrittenBy", resourceCulture);
            }
        }
    }
}
