//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.MedicalRecord.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.MedicalRecord.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show revisions.
        /// </summary>
        internal static string Btn_Revisions {
            get {
                return ResourceManager.GetString("Btn_Revisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger cette révision.
        /// </summary>
        internal static string Btn_Rollback {
            get {
                return ResourceManager.GetString("Btn_Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Btn_SearchFor {
            get {
                return ResourceManager.GetString("Btn_SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string Edition_Bold {
            get {
                return ResourceManager.GetString("Edition_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullets.
        /// </summary>
        internal static string Edition_Bullets {
            get {
                return ResourceManager.GetString("Edition_Bullets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center align.
        /// </summary>
        internal static string Edition_CenterAlign {
            get {
                return ResourceManager.GetString("Edition_CenterAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string Edition_Italic {
            get {
                return ResourceManager.GetString("Edition_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify align.
        /// </summary>
        internal static string Edition_JustifyAlign {
            get {
                return ResourceManager.GetString("Edition_JustifyAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left align.
        /// </summary>
        internal static string Edition_LeftAlign {
            get {
                return ResourceManager.GetString("Edition_LeftAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering.
        /// </summary>
        internal static string Edition_Numbering {
            get {
                return ResourceManager.GetString("Edition_Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right align.
        /// </summary>
        internal static string Edition_RightAlign {
            get {
                return ResourceManager.GetString("Edition_RightAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string Edition_Underline {
            get {
                return ResourceManager.GetString("Edition_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The macro is invalid.
        /// </summary>
        internal static string Err_InvalidMacro {
            get {
                return ResourceManager.GetString("Err_InvalidMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical records.
        /// </summary>
        internal static string Header_MedicalRecords {
            get {
                return ResourceManager.GetString("Header_MedicalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros.
        /// </summary>
        internal static string Lbl_Macros {
            get {
                return ResourceManager.GetString("Lbl_Macros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New macro.
        /// </summary>
        internal static string Macro_New {
            get {
                return ResourceManager.GetString("Macro_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        internal static string Menu_Edition {
            get {
                return ResourceManager.GetString("Menu_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Menu_Font {
            get {
                return ResourceManager.GetString("Menu_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        internal static string Menu_Paragraph {
            get {
                return ResourceManager.GetString("Menu_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading medical records. {0}.
        /// </summary>
        internal static string Msg_FailToLoadMedicalRecords {
            get {
                return ResourceManager.GetString("Msg_FailToLoadMedicalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro &apos;{0}&apos; removed..
        /// </summary>
        internal static string Msg_MacroRemoved {
            get {
                return ResourceManager.GetString("Msg_MacroRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros have been updated..
        /// </summary>
        internal static string Msg_MacrosUpdated {
            get {
                return ResourceManager.GetString("Msg_MacrosUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New card added to the record.
        /// </summary>
        internal static string Msg_RecordAdded {
            get {
                return ResourceManager.GetString("Msg_RecordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical record saved..
        /// </summary>
        internal static string Msg_RecordsSaved {
            get {
                return ResourceManager.GetString("Msg_RecordsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save this medical record?.
        /// </summary>
        internal static string Msg_SaveMedicalRecord {
            get {
                return ResourceManager.GetString("Msg_SaveMedicalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; was created.
        /// </summary>
        internal static string Msg_TagAdded {
            get {
                return ResourceManager.GetString("Msg_TagAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create a new macro? If you don&apos;t save modification of the current macro, all the modification will be lost..
        /// </summary>
        internal static string Question_CreateMacro {
            get {
                return ResourceManager.GetString("Question_CreateMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous supprimer la macro &apos;{0}&apos;?.
        /// </summary>
        internal static string Question_RemoveMacro {
            get {
                return ResourceManager.GetString("Question_RemoveMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default&apos;s editor font.
        /// </summary>
        internal static string Settings_DefaultFont {
            get {
                return ResourceManager.GetString("Settings_DefaultFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        internal static string Settings_FontFamily {
            get {
                return ResourceManager.GetString("Settings_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample text.
        /// </summary>
        internal static string Settings_Sample {
            get {
                return ResourceManager.GetString("Settings_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Weight Stretch.
        /// </summary>
        internal static string Settings_Style {
            get {
                return ResourceManager.GetString("Settings_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new directory.
        /// </summary>
        internal static string Title_AddFolder {
            get {
                return ResourceManager.GetString("Title_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new card.
        /// </summary>
        internal static string Title_AddRecord {
            get {
                return ResourceManager.GetString("Title_AddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Title_BtnAdd {
            get {
                return ResourceManager.GetString("Title_BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New macro.
        /// </summary>
        internal static string Title_DefaultMacroTitle {
            get {
                return ResourceManager.GetString("Title_DefaultMacroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit macros.
        /// </summary>
        internal static string Title_Macro {
            get {
                return ResourceManager.GetString("Title_Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of the macro:.
        /// </summary>
        internal static string Title_MacroName {
            get {
                return ResourceManager.GetString("Title_MacroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical record.
        /// </summary>
        internal static string Title_MedicalRecord {
            get {
                return ResourceManager.GetString("Title_MedicalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | Created {1} | Last update: {2}.
        /// </summary>
        internal static string Title_MedicalRecordTitle {
            get {
                return ResourceManager.GetString("Title_MedicalRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisions history.
        /// </summary>
        internal static string Title_Rollback {
            get {
                return ResourceManager.GetString("Title_Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Title_Save {
            get {
                return ResourceManager.GetString("Title_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for:.
        /// </summary>
        internal static string Title_SearchFor {
            get {
                return ResourceManager.GetString("Title_SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Title_Tools {
            get {
                return ResourceManager.GetString("Title_Tools", resourceCulture);
            }
        }
    }
}
