//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.UserSession.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.UserSession.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage my personal data.
        /// </summary>
        internal static string Menu_ManagePersonalData {
            get {
                return ResourceManager.GetString("Menu_ManagePersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print card.
        /// </summary>
        internal static string Menu_Print {
            get {
                return ResourceManager.GetString("Menu_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add this user?.
        /// </summary>
        internal static string Msg_AskAddUser {
            get {
                return ResourceManager.GetString("Msg_AskAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string Msg_Connection {
            get {
                return ResourceManager.GetString("Msg_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the administrator.
        /// </summary>
        internal static string Msg_CreateAdministrator {
            get {
                return ResourceManager.GetString("Msg_CreateAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while adding a new user.
        /// </summary>
        internal static string Msg_ErrorAddUser {
            get {
                return ResourceManager.GetString("Msg_ErrorAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while changing the password.
        /// </summary>
        internal static string Msg_ErrorChangingPwd {
            get {
                return ResourceManager.GetString("Msg_ErrorChangingPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while updating the user.
        /// </summary>
        internal static string Msg_ErrorUpdateUser {
            get {
                return ResourceManager.GetString("Msg_ErrorUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading the data of a user..
        /// </summary>
        internal static string Msg_ErrorWhileLoadingUser {
            get {
                return ResourceManager.GetString("Msg_ErrorWhileLoadingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        internal static string Msg_ErrorWrongPassword {
            get {
                return ResourceManager.GetString("Msg_ErrorWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet implemented.
        /// </summary>
        internal static string Msg_NotYetImplemented {
            get {
                return ResourceManager.GetString("Msg_NotYetImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated..
        /// </summary>
        internal static string Msg_PwdChanged {
            get {
                return ResourceManager.GetString("Msg_PwdChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string Msg_Ready {
            get {
                return ResourceManager.GetString("Msg_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user has been added..
        /// </summary>
        internal static string Msg_UserAdded {
            get {
                return ResourceManager.GetString("Msg_UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated.
        /// </summary>
        internal static string Msg_UserUpdated {
            get {
                return ResourceManager.GetString("Msg_UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bear in mind that this action will replace any configured default patient. Do you want to set yourself as the default user?.
        /// </summary>
        internal static string Msg_WarnDefaultUser {
            get {
                return ResourceManager.GetString("Msg_WarnDefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reenter the pwd.
        /// </summary>
        internal static string Title_AgainPwd {
            get {
                return ResourceManager.GetString("Title_AgainPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business card.
        /// </summary>
        internal static string Title_BusinessCard {
            get {
                return ResourceManager.GetString("Title_BusinessCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new user.
        /// </summary>
        internal static string Title_ButtonAddUser {
            get {
                return ResourceManager.GetString("Title_ButtonAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change my password.
        /// </summary>
        internal static string Title_ChangePwd {
            get {
                return ResourceManager.GetString("Title_ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User management.
        /// </summary>
        internal static string Title_ContextMenu {
            get {
                return ResourceManager.GetString("Title_ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load this user by default..
        /// </summary>
        internal static string Title_DefaultUser {
            get {
                return ResourceManager.GetString("Title_DefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        internal static string Title_Fee {
            get {
                return ResourceManager.GetString("Title_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        internal static string Title_FirstName {
            get {
                return ResourceManager.GetString("Title_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header:.
        /// </summary>
        internal static string Title_Header {
            get {
                return ResourceManager.GetString("Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Title_Info {
            get {
                return ResourceManager.GetString("Title_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        internal static string Title_LastName {
            get {
                return ResourceManager.GetString("Title_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail pro:.
        /// </summary>
        internal static string Title_MailPro {
            get {
                return ResourceManager.GetString("Title_MailPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile pro:.
        /// </summary>
        internal static string Title_MobilePro {
            get {
                return ResourceManager.GetString("Title_MobilePro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password:.
        /// </summary>
        internal static string Title_OldPwd {
            get {
                return ResourceManager.GetString("Title_OldPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Title_Password {
            get {
                return ResourceManager.GetString("Title_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone pro:.
        /// </summary>
        internal static string Title_PhonePro {
            get {
                return ResourceManager.GetString("Title_PhonePro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical practice:.
        /// </summary>
        internal static string Title_Practice {
            get {
                return ResourceManager.GetString("Title_Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Title_Question {
            get {
                return ResourceManager.GetString("Title_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        internal static string Title_RepeatPasword {
            get {
                return ResourceManager.GetString("Title_RepeatPasword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Title_Role {
            get {
                return ResourceManager.GetString("Title_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Title_SepContact {
            get {
                return ResourceManager.GetString("Title_SepContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string Title_SepHeader {
            get {
                return ResourceManager.GetString("Title_SepHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string Title_SepMisc {
            get {
                return ResourceManager.GetString("Title_SepMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        internal static string Title_SepPersonalData {
            get {
                return ResourceManager.GetString("Title_SepPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string Title_ValidatePwdChange {
            get {
                return ResourceManager.GetString("Title_ValidatePwdChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
    }
}
