//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.MeetingManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.MeetingManager.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Btn_Remove {
            get {
                return ResourceManager.GetString("Btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while searching tags.
        /// </summary>
        internal static string Error_CantFindTags {
            get {
                return ResourceManager.GetString("Error_CantFindTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when creating a appointment.
        /// </summary>
        internal static string Error_DuringAppointmentAdd {
            get {
                return ResourceManager.GetString("Error_DuringAppointmentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when removing a appointment.
        /// </summary>
        internal static string Error_DuringAppointmentRemove {
            get {
                return ResourceManager.GetString("Error_DuringAppointmentRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while searching.
        /// </summary>
        internal static string Error_ErrorSearching {
            get {
                return ResourceManager.GetString("Error_ErrorSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while refreshing calendar.
        /// </summary>
        internal static string Error_RefreshingCalendar {
            get {
                return ResourceManager.GetString("Error_RefreshingCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Header_Add {
            get {
                return ResourceManager.GetString("Header_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Header_Remove {
            get {
                return ResourceManager.GetString("Header_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a appointment.
        /// </summary>
        internal static string Lbl_AddMeeting {
            get {
                return ResourceManager.GetString("Lbl_AddMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And:.
        /// </summary>
        internal static string Lbl_And {
            get {
                return ResourceManager.GetString("Lbl_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between:.
        /// </summary>
        internal static string Lbl_Between {
            get {
                return ResourceManager.GetString("Lbl_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binded calendar:.
        /// </summary>
        internal static string Lbl_BindedCalendar {
            get {
                return ResourceManager.GetString("Lbl_BindedCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment list:.
        /// </summary>
        internal static string Lbl_BusySlots {
            get {
                return ResourceManager.GetString("Lbl_BusySlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Google Calendar binding?.
        /// </summary>
        internal static string Lbl_CalendarActivated {
            get {
                return ResourceManager.GetString("Lbl_CalendarActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free slots:.
        /// </summary>
        internal static string Lbl_FreeSlots {
            get {
                return ResourceManager.GetString("Lbl_FreeSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Lbl_Password {
            get {
                return ResourceManager.GetString("Lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a meeting.
        /// </summary>
        internal static string Lbl_RemoveMeeting {
            get {
                return ResourceManager.GetString("Lbl_RemoveMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected patient:.
        /// </summary>
        internal static string Lbl_SelectedPatient {
            get {
                return ResourceManager.GetString("Lbl_SelectedPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        internal static string Lbl_UserName {
            get {
                return ResourceManager.GetString("Lbl_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a category.
        /// </summary>
        internal static string Msg_AddCategory {
            get {
                return ResourceManager.GetString("Msg_AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An appointment has just been added.
        /// </summary>
        internal static string Msg_AppointmentAdded {
            get {
                return ResourceManager.GetString("Msg_AppointmentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add this appointment?.
        /// </summary>
        internal static string Msg_AppointmentAskAdd {
            get {
                return ResourceManager.GetString("Msg_AppointmentAskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove this appointment?.
        /// </summary>
        internal static string Msg_AppointmentAskRemove {
            get {
                return ResourceManager.GetString("Msg_AppointmentAskRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An appointment has just been removed..
        /// </summary>
        internal static string Msg_AppointmentRemoved {
            get {
                return ResourceManager.GetString("Msg_AppointmentRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category added.
        /// </summary>
        internal static string Msg_CategoryAdded {
            get {
                return ResourceManager.GetString("Msg_CategoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the loading of the calendar.
        /// </summary>
        internal static string Msg_FailToLoadCalendar {
            get {
                return ResourceManager.GetString("Msg_FailToLoadCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result.
        /// </summary>
        internal static string Msg_NothingFound {
            get {
                return ResourceManager.GetString("Msg_NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search processed..
        /// </summary>
        internal static string Msg_SearchProcessed {
            get {
                return ResourceManager.GetString("Msg_SearchProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        internal static string SlotDuration_OneHour {
            get {
                return ResourceManager.GetString("SlotDuration_OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        internal static string SlotDuration_ThirtyMinutes {
            get {
                return ResourceManager.GetString("SlotDuration_ThirtyMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a appointment.
        /// </summary>
        internal static string Title_AddMeeting {
            get {
                return ResourceManager.GetString("Title_AddMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Title_Calendar {
            get {
                return ResourceManager.GetString("Title_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string Title_End {
            get {
                return ResourceManager.GetString("Title_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from {1} to {2} {3}.
        /// </summary>
        internal static string Title_FromTo {
            get {
                return ResourceManager.GetString("Title_FromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Title_MeetingsManager {
            get {
                return ResourceManager.GetString("Title_MeetingsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Title_Question {
            get {
                return ResourceManager.GetString("Title_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove an appointment.
        /// </summary>
        internal static string Title_RemoveMeeting {
            get {
                return ResourceManager.GetString("Title_RemoveMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First or last name.
        /// </summary>
        internal static string Title_SearchWatermark {
            get {
                return ResourceManager.GetString("Title_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot duration.
        /// </summary>
        internal static string Title_SlotDuration {
            get {
                return ResourceManager.GetString("Title_SlotDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Title_Start {
            get {
                return ResourceManager.GetString("Title_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Title_Subject {
            get {
                return ResourceManager.GetString("Title_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Title_Tag {
            get {
                return ResourceManager.GetString("Title_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workday.
        /// </summary>
        internal static string Title_Workday {
            get {
                return ResourceManager.GetString("Title_Workday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;heure de début de la journée de travail doit être plus petite que l&apos;heure de fin.
        /// </summary>
        internal static string Warn_CalendarSettingsNotSaved {
            get {
                return ResourceManager.GetString("Warn_CalendarSettingsNotSaved", resourceCulture);
            }
        }
    }
}
