//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.MeetingManager.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.MeetingManager.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Btn_Remove {
            get {
                return ResourceManager.GetString("Btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while searching tags.
        /// </summary>
        internal static string Error_CantFindTags {
            get {
                return ResourceManager.GetString("Error_CantFindTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when creating a appointment.
        /// </summary>
        internal static string Error_DuringAppointmentAdd {
            get {
                return ResourceManager.GetString("Error_DuringAppointmentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when removing a appointment.
        /// </summary>
        internal static string Error_DuringAppointmentRemove {
            get {
                return ResourceManager.GetString("Error_DuringAppointmentRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while searching.
        /// </summary>
        internal static string Error_ErrorSearching {
            get {
                return ResourceManager.GetString("Error_ErrorSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while refreshing calendar.
        /// </summary>
        internal static string Error_RefreshingCalendar {
            get {
                return ResourceManager.GetString("Error_RefreshingCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Header_Add {
            get {
                return ResourceManager.GetString("Header_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Header_Remove {
            get {
                return ResourceManager.GetString("Header_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une rendez-vous a été ajouté..
        /// </summary>
        internal static string Msg_AppointmentAdded {
            get {
                return ResourceManager.GetString("Msg_AppointmentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add this appointment?.
        /// </summary>
        internal static string Msg_AppointmentAskAdd {
            get {
                return ResourceManager.GetString("Msg_AppointmentAskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove this appointment?.
        /// </summary>
        internal static string Msg_AppointmentAskRemove {
            get {
                return ResourceManager.GetString("Msg_AppointmentAskRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An appointment has just been removed..
        /// </summary>
        internal static string Msg_AppointmentRemoved {
            get {
                return ResourceManager.GetString("Msg_AppointmentRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the loading of the calendar.
        /// </summary>
        internal static string Msg_FailToLoadCalendar {
            get {
                return ResourceManager.GetString("Msg_FailToLoadCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search processed..
        /// </summary>
        internal static string Msg_SearchProcessed {
            get {
                return ResourceManager.GetString("Msg_SearchProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Title_Calendar {
            get {
                return ResourceManager.GetString("Title_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from {1} to {2} {3}.
        /// </summary>
        internal static string Title_FromTo {
            get {
                return ResourceManager.GetString("Title_FromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Title_Question {
            get {
                return ResourceManager.GetString("Title_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Title_Subject {
            get {
                return ResourceManager.GetString("Title_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Title_Tag {
            get {
                return ResourceManager.GetString("Title_Tag", resourceCulture);
            }
        }
    }
}
