//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.MedicalRecord.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.MedicalRecord.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Btn_SearchFor {
            get {
                return ResourceManager.GetString("Btn_SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string Edition_Bold {
            get {
                return ResourceManager.GetString("Edition_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullets.
        /// </summary>
        internal static string Edition_Bullets {
            get {
                return ResourceManager.GetString("Edition_Bullets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center align.
        /// </summary>
        internal static string Edition_CenterAlign {
            get {
                return ResourceManager.GetString("Edition_CenterAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string Edition_Italic {
            get {
                return ResourceManager.GetString("Edition_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify align.
        /// </summary>
        internal static string Edition_JustifyAlign {
            get {
                return ResourceManager.GetString("Edition_JustifyAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left align.
        /// </summary>
        internal static string Edition_LeftAlign {
            get {
                return ResourceManager.GetString("Edition_LeftAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering.
        /// </summary>
        internal static string Edition_Numbering {
            get {
                return ResourceManager.GetString("Edition_Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right align.
        /// </summary>
        internal static string Edition_RightAlign {
            get {
                return ResourceManager.GetString("Edition_RightAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string Edition_Underline {
            get {
                return ResourceManager.GetString("Edition_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        internal static string Menu_Edition {
            get {
                return ResourceManager.GetString("Menu_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Menu_Font {
            get {
                return ResourceManager.GetString("Menu_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        internal static string Menu_Paragraph {
            get {
                return ResourceManager.GetString("Menu_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading medical records. {0}.
        /// </summary>
        internal static string Msg_FailToLoadMedicalRecords {
            get {
                return ResourceManager.GetString("Msg_FailToLoadMedicalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New card added to the record.
        /// </summary>
        internal static string Msg_RecordAdded {
            get {
                return ResourceManager.GetString("Msg_RecordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical record saved..
        /// </summary>
        internal static string Msg_RecordsSaved {
            get {
                return ResourceManager.GetString("Msg_RecordsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; was created.
        /// </summary>
        internal static string Msg_TagAdded {
            get {
                return ResourceManager.GetString("Msg_TagAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new directory.
        /// </summary>
        internal static string Title_AddFolder {
            get {
                return ResourceManager.GetString("Title_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new card.
        /// </summary>
        internal static string Title_AddRecord {
            get {
                return ResourceManager.GetString("Title_AddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Title_BtnAdd {
            get {
                return ResourceManager.GetString("Title_BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical record.
        /// </summary>
        internal static string Title_MedicalRecord {
            get {
                return ResourceManager.GetString("Title_MedicalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Title_Save {
            get {
                return ResourceManager.GetString("Title_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for:.
        /// </summary>
        internal static string Title_SearchFor {
            get {
                return ResourceManager.GetString("Title_SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Title_Tools {
            get {
                return ResourceManager.GetString("Title_Tools", resourceCulture);
            }
        }
    }
}
