//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Domain.DAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Domain.DAL.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one default user was found..
        /// </summary>
        internal static string Ex_QueryException_SeveralDefaultUsers {
            get {
                return ResourceManager.GetString("Ex_QueryException_SeveralDefaultUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to create the database.
        /// </summary>
        internal static string Msg_ErrorDbCreationImpossible {
            get {
                return ResourceManager.GetString("Msg_ErrorDbCreationImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the database is invalid or the file doesn&apos;t exist.
        /// </summary>
        internal static string Msg_ErrorDbInvalidPath {
            get {
                return ResourceManager.GetString("Msg_ErrorDbInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path where to export the HBM files is invalid or doesn&apos;t exist!.
        /// </summary>
        internal static string Msg_ErrorInvalidHbmPath {
            get {
                return ResourceManager.GetString("Msg_ErrorInvalidHbmPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A session is already opened. Please, close the opened session before opening a new one..
        /// </summary>
        internal static string Msg_ErrorSessionAlreadyOpenException {
            get {
                return ResourceManager.GetString("Msg_ErrorSessionAlreadyOpenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session factory is not set. Are you sure you have configured nHibernate for this instance?.
        /// </summary>
        internal static string Msg_ErrorSessionFactoryNull {
            get {
                return ResourceManager.GetString("Msg_ErrorSessionFactoryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session is not open. Please open it before querying the database..
        /// </summary>
        internal static string Msg_ErrorSessionNotOpen {
            get {
                return ResourceManager.GetString("Msg_ErrorSessionNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQLiteConfiguration is not set!.
        /// </summary>
        internal static string Msg_ErrorSQLiteConfigurationNotSet {
            get {
                return ResourceManager.GetString("Msg_ErrorSQLiteConfigurationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t entered twice the same password. .
        /// </summary>
        internal static string Validation_Password {
            get {
                return ResourceManager.GetString("Validation_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password can&apos;t be empty.
        /// </summary>
        internal static string Validation_PasswordCantBeEmpty {
            get {
                return ResourceManager.GetString("Validation_PasswordCantBeEmpty", resourceCulture);
            }
        }
    }
}
