//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.PathologyManager.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.PathologyManager.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Btn_Remove {
            get {
                return ResourceManager.GetString("Btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (days).
        /// </summary>
        internal static string Header_Duration {
            get {
                return ResourceManager.GetString("Header_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string Header_End {
            get {
                return ResourceManager.GetString("Header_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathology.
        /// </summary>
        internal static string Header_Pathology {
            get {
                return ResourceManager.GetString("Header_Pathology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Header_Start {
            get {
                return ResourceManager.GetString("Header_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add this illness period?.
        /// </summary>
        internal static string Msg_AskAddNewPeriod {
            get {
                return ResourceManager.GetString("Msg_AskAddNewPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new category was added.
        /// </summary>
        internal static string Msg_CategoryAdded {
            get {
                return ResourceManager.GetString("Msg_CategoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this period?.
        /// </summary>
        internal static string Msg_DeleteIllnessPeriod {
            get {
                return ResourceManager.GetString("Msg_DeleteIllnessPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue. Vérifier les logs pour plus d&apos;informations..
        /// </summary>
        internal static string Msg_ErrorOccured {
            get {
                return ResourceManager.GetString("Msg_ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Use the search box to find the pathology. 
        ///* In the list, click on the pathology
        ///* Choose the begin and the end date of the pathology period. 
        ///* Click on &quot;Add&quot;.
        /// </summary>
        internal static string Msg_ExplainHowToAddPeriod {
            get {
                return ResourceManager.GetString("Msg_ExplainHowToAddPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while adding an illness period.
        /// </summary>
        internal static string Msg_FailAddIllnessPeriod {
            get {
                return ResourceManager.GetString("Msg_FailAddIllnessPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading the pathology manager..
        /// </summary>
        internal static string Msg_FailToLoadPathologyManager {
            get {
                return ResourceManager.GetString("Msg_FailToLoadPathologyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illness period removed..
        /// </summary>
        internal static string Msg_IllnessRemoved {
            get {
                return ResourceManager.GetString("Msg_IllnessRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle période de maladie ajoutée..
        /// </summary>
        internal static string Msg_PeriodAdded {
            get {
                return ResourceManager.GetString("Msg_PeriodAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Title_Add {
            get {
                return ResourceManager.GetString("Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a pathology.
        /// </summary>
        internal static string Title_AddPathology {
            get {
                return ResourceManager.GetString("Title_AddPathology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add pathology category.
        /// </summary>
        internal static string Title_AddPathologyCategory {
            get {
                return ResourceManager.GetString("Title_AddPathologyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a period.
        /// </summary>
        internal static string Title_AddPeriods {
            get {
                return ResourceManager.GetString("Title_AddPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        internal static string Title_Chart {
            get {
                return ResourceManager.GetString("Title_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart showing illness time.
        /// </summary>
        internal static string Title_ChartIllnessTime {
            get {
                return ResourceManager.GetString("Title_ChartIllnessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        internal static string Title_Charts {
            get {
                return ResourceManager.GetString("Title_Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw data.
        /// </summary>
        internal static string Title_Data {
            get {
                return ResourceManager.GetString("Title_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string Title_From {
            get {
                return ResourceManager.GetString("Title_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ill from.
        /// </summary>
        internal static string Title_IllFrom {
            get {
                return ResourceManager.GetString("Title_IllFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s).
        /// </summary>
        internal static string Title_IllnessDuration {
            get {
                return ResourceManager.GetString("Title_IllnessDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End: {0}.
        /// </summary>
        internal static string Title_IllnessEndsAt {
            get {
                return ResourceManager.GetString("Title_IllnessEndsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start: {0}.
        /// </summary>
        internal static string Title_IllnessStartsAt {
            get {
                return ResourceManager.GetString("Title_IllnessStartsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation succeeded..
        /// </summary>
        internal static string Title_OperationDone {
            get {
                return ResourceManager.GetString("Title_OperationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathologies.
        /// </summary>
        internal static string Title_PathologyManager {
            get {
                return ResourceManager.GetString("Title_PathologyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Title_Question {
            get {
                return ResourceManager.GetString("Title_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Title_SearchWatermark {
            get {
                return ResourceManager.GetString("Title_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Title_To {
            get {
                return ResourceManager.GetString("Title_To", resourceCulture);
            }
        }
    }
}
