//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.Administration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.Administration.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Btn_Apply {
            get {
                return ResourceManager.GetString("Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved.
        /// </summary>
        internal static string Msg_DataSaved {
            get {
                return ResourceManager.GetString("Msg_DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Check the logs for further information..
        /// </summary>
        internal static string Msg_ErrorOccured {
            get {
                return ResourceManager.GetString("Msg_ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administer.
        /// </summary>
        internal static string Title_AdministratorManager {
            get {
                return ResourceManager.GetString("Title_AdministratorManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box nr.
        /// </summary>
        internal static string Title_BoxNr {
            get {
                return ResourceManager.GetString("Title_BoxNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Title_City {
            get {
                return ResourceManager.GetString("Title_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug.
        /// </summary>
        internal static string Title_Drug {
            get {
                return ResourceManager.GetString("Title_Drug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        internal static string Title_Insurance {
            get {
                return ResourceManager.GetString("Title_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string Title_Name {
            get {
                return ResourceManager.GetString("Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Title_Notes {
            get {
                return ResourceManager.GetString("Title_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathology.
        /// </summary>
        internal static string Title_Pathology {
            get {
                return ResourceManager.GetString("Title_Pathology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Title_Phone {
            get {
                return ResourceManager.GetString("Title_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        internal static string Title_PostalCode {
            get {
                return ResourceManager.GetString("Title_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical practice.
        /// </summary>
        internal static string Title_Practice {
            get {
                return ResourceManager.GetString("Title_Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string Title_Profession {
            get {
                return ResourceManager.GetString("Title_Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation.
        /// </summary>
        internal static string Title_Reputation {
            get {
                return ResourceManager.GetString("Title_Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialisation.
        /// </summary>
        internal static string Title_Specialisation {
            get {
                return ResourceManager.GetString("Title_Specialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Title_Street {
            get {
                return ResourceManager.GetString("Title_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr.
        /// </summary>
        internal static string Title_StreetNr {
            get {
                return ResourceManager.GetString("Title_StreetNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Title_Tag {
            get {
                return ResourceManager.GetString("Title_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Title_Type {
            get {
                return ResourceManager.GetString("Title_Type", resourceCulture);
            }
        }
    }
}
