//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Probel.NDoctor.View.Core.ServiceReference
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IStatLogger")]
    public interface IStatLogger
    {
        #region Methods

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatLogger/Register", ReplyAction="http://tempuri.org/IStatLogger/RegisterResponse")]
        void Register(string serial, string version, string application);

        #endregion Methods
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStatLoggerChannel : Probel.NDoctor.View.Core.ServiceReference.IStatLogger, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatLoggerClient : System.ServiceModel.ClientBase<Probel.NDoctor.View.Core.ServiceReference.IStatLogger>, Probel.NDoctor.View.Core.ServiceReference.IStatLogger
    {
        #region Constructors

        public StatLoggerClient()
        {
        }

        public StatLoggerClient(string endpointConfigurationName)
            : base(endpointConfigurationName)
        {
        }

        public StatLoggerClient(string endpointConfigurationName, string remoteAddress)
            : base(endpointConfigurationName, remoteAddress)
        {
        }

        public StatLoggerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
            : base(endpointConfigurationName, remoteAddress)
        {
        }

        public StatLoggerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
            : base(binding, remoteAddress)
        {
        }

        #endregion Constructors

        #region Methods

        public void Register(string serial, string version, string application)
        {
            base.Channel.Register(serial, version, application);
        }

        #endregion Methods
    }
}