//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.PrescriptionManager.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.PrescriptionManager.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a drug.
        /// </summary>
        internal static string Btn_AddDrug {
            get {
                return ResourceManager.GetString("Btn_AddDrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a drug type.
        /// </summary>
        internal static string Btn_AddDrugType {
            get {
                return ResourceManager.GetString("Btn_AddDrugType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouv..
        /// </summary>
        internal static string Btn_New {
            get {
                return ResourceManager.GetString("Btn_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this prescription.
        /// </summary>
        internal static string Btn_Remove {
            get {
                return ResourceManager.GetString("Btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Btn_Select {
            get {
                return ResourceManager.GetString("Btn_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs.
        /// </summary>
        internal static string Col_Drugs {
            get {
                return ResourceManager.GetString("Col_Drugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Col_Notes {
            get {
                return ResourceManager.GetString("Col_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string Menu_Manage {
            get {
                return ResourceManager.GetString("Menu_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Menu_Navigation {
            get {
                return ResourceManager.GetString("Menu_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved.
        /// </summary>
        internal static string Msg_DataSaved {
            get {
                return ResourceManager.GetString("Msg_DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il existe des prescriptions sans notes. Voulez-vous continuer?.
        /// </summary>
        internal static string Msg_EmptyNotesForPrescriptions {
            get {
                return ResourceManager.GetString("Msg_EmptyNotesForPrescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Check the logs for further information..
        /// </summary>
        internal static string Msg_ErrorOccured {
            get {
                return ResourceManager.GetString("Msg_ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving the prescription..
        /// </summary>
        internal static string Msg_ErrorSavingPrescription {
            get {
                return ResourceManager.GetString("Msg_ErrorSavingPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while searching prescriptions..
        /// </summary>
        internal static string Msg_ErrorSearchingPrescriptions {
            get {
                return ResourceManager.GetString("Msg_ErrorSearchingPrescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescriptions were found.
        /// </summary>
        internal static string Msg_FoundPrescription {
            get {
                return ResourceManager.GetString("Msg_FoundPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was found.
        /// </summary>
        internal static string Msg_NothingFound {
            get {
                return ResourceManager.GetString("Msg_NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prescription wasn&apos;t saved. Please enter at least one drug..
        /// </summary>
        internal static string Msg_NothingToSave {
            get {
                return ResourceManager.GetString("Msg_NothingToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription deleted..
        /// </summary>
        internal static string Msg_PrescriptionDeleted {
            get {
                return ResourceManager.GetString("Msg_PrescriptionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription saved..
        /// </summary>
        internal static string Msg_PrescriptionSaved {
            get {
                return ResourceManager.GetString("Msg_PrescriptionSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter notes here:.
        /// </summary>
        internal static string Title_AddNotesHere {
            get {
                return ResourceManager.GetString("Title_AddNotesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new prescription.
        /// </summary>
        internal static string Title_AddPrescription {
            get {
                return ResourceManager.GetString("Title_AddPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of a prescription.
        /// </summary>
        internal static string Title_CreatePrescription {
            get {
                return ResourceManager.GetString("Title_CreatePrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date:.
        /// </summary>
        internal static string Title_CreationDate {
            get {
                return ResourceManager.GetString("Title_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this prescription.
        /// </summary>
        internal static string Title_EditPrescription {
            get {
                return ResourceManager.GetString("Title_EditPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string Title_From {
            get {
                return ResourceManager.GetString("Title_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Title_Name {
            get {
                return ResourceManager.GetString("Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation succeeded..
        /// </summary>
        internal static string Title_OperationDone {
            get {
                return ResourceManager.GetString("Title_OperationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag:.
        /// </summary>
        internal static string Title_PrescripitonTag {
            get {
                return ResourceManager.GetString("Title_PrescripitonTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription created on:.
        /// </summary>
        internal static string Title_PrescriptionDocumentCreated {
            get {
                return ResourceManager.GetString("Title_PrescriptionDocumentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescriptions list between {0} and {1}.
        /// </summary>
        internal static string Title_PrescriptionHeader {
            get {
                return ResourceManager.GetString("Title_PrescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescriptions.
        /// </summary>
        internal static string Title_PrescriptionManager {
            get {
                return ResourceManager.GetString("Title_PrescriptionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Title_PrescriptionNotes {
            get {
                return ResourceManager.GetString("Title_PrescriptionNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search drugs.
        /// </summary>
        internal static string Title_SearchDrugs {
            get {
                return ResourceManager.GetString("Title_SearchDrugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Title_SearchWatermark {
            get {
                return ResourceManager.GetString("Title_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected drug.
        /// </summary>
        internal static string Title_SelectedDrug {
            get {
                return ResourceManager.GetString("Title_SelectedDrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Title_Tag {
            get {
                return ResourceManager.GetString("Title_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Title_To {
            get {
                return ResourceManager.GetString("Title_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
