//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.PatientSession.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.PatientSession.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while adding a new patient.
        /// </summary>
        internal static string Error_AddPatient {
            get {
                return ResourceManager.GetString("Error_AddPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Menu_Select {
            get {
                return ResourceManager.GetString("Menu_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient added..
        /// </summary>
        internal static string Msg_PatientAdded {
            get {
                return ResourceManager.GetString("Msg_PatientAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient selected.
        /// </summary>
        internal static string Msg_PatientSelected {
            get {
                return ResourceManager.GetString("Msg_PatientSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} patient(s) found..
        /// </summary>
        internal static string Msg_SearchExecuted {
            get {
                return ResourceManager.GetString("Msg_SearchExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a session for {0}.
        /// </summary>
        internal static string Msg_SelectPatient {
            get {
                return ResourceManager.GetString("Msg_SelectPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Title_Add {
            get {
                return ResourceManager.GetString("Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a patient.
        /// </summary>
        internal static string Title_AddPatient {
            get {
                return ResourceManager.GetString("Title_AddPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a patient.
        /// </summary>
        internal static string Title_ButtonAddPatient {
            get {
                return ResourceManager.GetString("Title_ButtonAddPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Title_ButtonSearch {
            get {
                return ResourceManager.GetString("Title_ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string Title_FirstName {
            get {
                return ResourceManager.GetString("Title_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Title_Gender {
            get {
                return ResourceManager.GetString("Title_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Title_LastName {
            get {
                return ResourceManager.GetString("Title_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten most used patients.
        /// </summary>
        internal static string Title_MostUsed {
            get {
                return ResourceManager.GetString("Title_MostUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search patient.
        /// </summary>
        internal static string Title_SearchPatient {
            get {
                return ResourceManager.GetString("Title_SearchPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First or last name.
        /// </summary>
        internal static string Title_SearchWatermark {
            get {
                return ResourceManager.GetString("Title_SearchWatermark", resourceCulture);
            }
        }
    }
}
