//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.PatientData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.PatientData.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to patient.
        /// </summary>
        internal static string Btn_AddDoctor {
            get {
                return ResourceManager.GetString("Btn_AddDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to load the patient. {0}.
        /// </summary>
        internal static string Ex_PatientLoadException {
            get {
                return ResourceManager.GetString("Ex_PatientLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialisation.
        /// </summary>
        internal static string Header_DoctorSpecialisation {
            get {
                return ResourceManager.GetString("Header_DoctorSpecialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Header_DotorName {
            get {
                return ResourceManager.GetString("Header_DotorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Menu_Add {
            get {
                return ResourceManager.GetString("Menu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add this doctor to this patient?.
        /// </summary>
        internal static string Msg_AskAddDoctor {
            get {
                return ResourceManager.GetString("Msg_AskAddDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the link between the patient and the doctor?.
        /// </summary>
        internal static string Msg_AskRemoveLink {
            get {
                return ResourceManager.GetString("Msg_AskRemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change picture....
        /// </summary>
        internal static string Msg_ChangePicture {
            get {
                return ResourceManager.GetString("Msg_ChangePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved.
        /// </summary>
        internal static string Msg_DataSaved {
            get {
                return ResourceManager.GetString("Msg_DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor added to the patient..
        /// </summary>
        internal static string Msg_DoctorAded {
            get {
                return ResourceManager.GetString("Msg_DoctorAded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lien retiré.
        /// </summary>
        internal static string Msg_DoctorRemoved {
            get {
                return ResourceManager.GetString("Msg_DoctorRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while adding a doctor to the patient.
        /// </summary>
        internal static string Msg_ErrorAddDoctor {
            get {
                return ResourceManager.GetString("Msg_ErrorAddDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Check the logs for further information..
        /// </summary>
        internal static string Msg_ErrorOccured {
            get {
                return ResourceManager.GetString("Msg_ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while removing the link.
        /// </summary>
        internal static string Msg_ErrorRemovingDoctor {
            get {
                return ResourceManager.GetString("Msg_ErrorRemovingDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to save the patient. {0}.
        /// </summary>
        internal static string Msg_ErrorSave {
            get {
                return ResourceManager.GetString("Msg_ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Msg_GenderFemale {
            get {
                return ResourceManager.GetString("Msg_GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Msg_GenderMale {
            get {
                return ResourceManager.GetString("Msg_GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record is complete.
        /// </summary>
        internal static string Msg_RecordComplete {
            get {
                return ResourceManager.GetString("Msg_RecordComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a doctor.
        /// </summary>
        internal static string Title_AddDoctor {
            get {
                return ResourceManager.GetString("Title_AddDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an insurance.
        /// </summary>
        internal static string Title_AddInsurance {
            get {
                return ResourceManager.GetString("Title_AddInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a practice.
        /// </summary>
        internal static string Title_AddPractice {
            get {
                return ResourceManager.GetString("Title_AddPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a profession.
        /// </summary>
        internal static string Title_AddProfession {
            get {
                return ResourceManager.GetString("Title_AddProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a reputation.
        /// </summary>
        internal static string Title_AddReputation {
            get {
                return ResourceManager.GetString("Title_AddReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box nr.
        /// </summary>
        internal static string Title_AddressBox {
            get {
                return ResourceManager.GetString("Title_AddressBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Title_AddressCity {
            get {
                return ResourceManager.GetString("Title_AddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        internal static string Title_AddressPostalCode {
            get {
                return ResourceManager.GetString("Title_AddressPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Title_AddressStreet {
            get {
                return ResourceManager.GetString("Title_AddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr.
        /// </summary>
        internal static string Title_AddressStreetNr {
            get {
                return ResourceManager.GetString("Title_AddressStreetNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a specialisation.
        /// </summary>
        internal static string Title_AddSpecialisation {
            get {
                return ResourceManager.GetString("Title_AddSpecialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind a doctor....
        /// </summary>
        internal static string Title_BindDoctor {
            get {
                return ResourceManager.GetString("Title_BindDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string Title_Birthdate {
            get {
                return ResourceManager.GetString("Title_Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient data.
        /// </summary>
        internal static string Title_ContextMenu {
            get {
                return ResourceManager.GetString("Title_ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Title_Data {
            get {
                return ResourceManager.GetString("Title_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription.
        /// </summary>
        internal static string Title_DateInscription {
            get {
                return ResourceManager.GetString("Title_DateInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update.
        /// </summary>
        internal static string Title_DateLastUpdate {
            get {
                return ResourceManager.GetString("Title_DateLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        internal static string Title_Doctors {
            get {
                return ResourceManager.GetString("Title_Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Title_EmailPrivate {
            get {
                return ResourceManager.GetString("Title_EmailPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email prof..
        /// </summary>
        internal static string Title_EmailPro {
            get {
                return ResourceManager.GetString("Title_EmailPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        internal static string Title_Fee {
            get {
                return ResourceManager.GetString("Title_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string Title_FirstName {
            get {
                return ResourceManager.GetString("Title_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Title_FullName {
            get {
                return ResourceManager.GetString("Title_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Title_Gender {
            get {
                return ResourceManager.GetString("Title_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        internal static string Title_Insurance {
            get {
                return ResourceManager.GetString("Title_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Title_LastName {
            get {
                return ResourceManager.GetString("Title_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Title_Name {
            get {
                return ResourceManager.GetString("Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Title_New {
            get {
                return ResourceManager.GetString("Title_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Title_Notes {
            get {
                return ResourceManager.GetString("Title_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation succeeded..
        /// </summary>
        internal static string Title_OperationDone {
            get {
                return ResourceManager.GetString("Title_OperationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient data.
        /// </summary>
        internal static string Title_PatientDataManager {
            get {
                return ResourceManager.GetString("Title_PatientDataManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Title_Phone {
            get {
                return ResourceManager.GetString("Title_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of birth.
        /// </summary>
        internal static string Title_PlaceOfBirth {
            get {
                return ResourceManager.GetString("Title_PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet médical.
        /// </summary>
        internal static string Title_Practice {
            get {
                return ResourceManager.GetString("Title_Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Title_PrivateMobile {
            get {
                return ResourceManager.GetString("Title_PrivateMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Title_PrivatePhone {
            get {
                return ResourceManager.GetString("Title_PrivatePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string Title_Profession {
            get {
                return ResourceManager.GetString("Title_Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof. mobile.
        /// </summary>
        internal static string Title_ProMobile {
            get {
                return ResourceManager.GetString("Title_ProMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof. phone.
        /// </summary>
        internal static string Title_ProPhone {
            get {
                return ResourceManager.GetString("Title_ProPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Title_Reason {
            get {
                return ResourceManager.GetString("Title_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the link between the patient and the doctor.
        /// </summary>
        internal static string Title_RemoveDoctor {
            get {
                return ResourceManager.GetString("Title_RemoveDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation.
        /// </summary>
        internal static string Title_Reputation {
            get {
                return ResourceManager.GetString("Title_Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel modifications.
        /// </summary>
        internal static string Title_Rollback {
            get {
                return ResourceManager.GetString("Title_Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Title_Save {
            get {
                return ResourceManager.GetString("Title_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact data.
        /// </summary>
        internal static string Title_SeparatorContactData {
            get {
                return ResourceManager.GetString("Title_SeparatorContactData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string Title_SeparatorMiscellaneous {
            get {
                return ResourceManager.GetString("Title_SeparatorMiscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        internal static string Title_SeparatorPersonalData {
            get {
                return ResourceManager.GetString("Title_SeparatorPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string Title_SeparatorPicture {
            get {
                return ResourceManager.GetString("Title_SeparatorPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialisation.
        /// </summary>
        internal static string Title_Specialisation {
            get {
                return ResourceManager.GetString("Title_Specialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Title_TabAddress {
            get {
                return ResourceManager.GetString("Title_TabAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Title_TabContact {
            get {
                return ResourceManager.GetString("Title_TabContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Title_TabPrivateContact {
            get {
                return ResourceManager.GetString("Title_TabPrivateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        internal static string Title_TabProContact {
            get {
                return ResourceManager.GetString("Title_TabProContact", resourceCulture);
            }
        }
    }
}
