//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.PatientOverview.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.PatientOverview.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Btn_Doctor {
            get {
                return ResourceManager.GetString("Btn_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        internal static string Btn_Insurance {
            get {
                return ResourceManager.GetString("Btn_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string Btn_Job {
            get {
                return ResourceManager.GetString("Btn_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical practice.
        /// </summary>
        internal static string Btn_Practice {
            get {
                return ResourceManager.GetString("Btn_Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation.
        /// </summary>
        internal static string Btn_Reputation {
            get {
                return ResourceManager.GetString("Btn_Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        internal static string Btn_Revert {
            get {
                return ResourceManager.GetString("Btn_Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialisation.
        /// </summary>
        internal static string Btn_Specialisation {
            get {
                return ResourceManager.GetString("Btn_Specialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when sending the mail..
        /// </summary>
        internal static string Err_CantSendMail {
            get {
                return ResourceManager.GetString("Err_CantSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Group_Add {
            get {
                return ResourceManager.GetString("Group_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked doctors.
        /// </summary>
        internal static string Group_LinkedDoctor {
            get {
                return ResourceManager.GetString("Group_LinkedDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Grp_Address {
            get {
                return ResourceManager.GetString("Grp_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Grp_Doctor {
            get {
                return ResourceManager.GetString("Grp_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        internal static string Grp_Doctors {
            get {
                return ResourceManager.GetString("Grp_Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        internal static string Grp_Insurance {
            get {
                return ResourceManager.GetString("Grp_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string Grp_Misc {
            get {
                return ResourceManager.GetString("Grp_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string Grp_Notes {
            get {
                return ResourceManager.GetString("Grp_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string Grp_Patient {
            get {
                return ResourceManager.GetString("Grp_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical practice.
        /// </summary>
        internal static string Grp_Practice {
            get {
                return ResourceManager.GetString("Grp_Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private contact.
        /// </summary>
        internal static string Grp_PrivateContact {
            get {
                return ResourceManager.GetString("Grp_PrivateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional contact.
        /// </summary>
        internal static string GrpProfContact {
            get {
                return ResourceManager.GetString("GrpProfContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age (.
        /// </summary>
        internal static string Lbl_Age {
            get {
                return ResourceManager.GetString("Lbl_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate:.
        /// </summary>
        internal static string Lbl_Birthdate {
            get {
                return ResourceManager.GetString("Lbl_Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string Lbl_BornIn {
            get {
                return ResourceManager.GetString("Lbl_BornIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born on.
        /// </summary>
        internal static string Lbl_BornOn {
            get {
                return ResourceManager.GetString("Lbl_BornOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box:.
        /// </summary>
        internal static string Lbl_Box {
            get {
                return ResourceManager.GetString("Lbl_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string Lbl_City {
            get {
                return ResourceManager.GetString("Lbl_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee:.
        /// </summary>
        internal static string Lbl_Fee {
            get {
                return ResourceManager.GetString("Lbl_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Lbl_FirstName {
            get {
                return ResourceManager.GetString("Lbl_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        internal static string Lbl_Gender {
            get {
                return ResourceManager.GetString("Lbl_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription:.
        /// </summary>
        internal static string Lbl_Inscription {
            get {
                return ResourceManager.GetString("Lbl_Inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string Lbl_LastName {
            get {
                return ResourceManager.GetString("Lbl_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update:.
        /// </summary>
        internal static string Lbl_LastUpdate {
            get {
                return ResourceManager.GetString("Lbl_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail:.
        /// </summary>
        internal static string Lbl_Mail {
            get {
                return ResourceManager.GetString("Lbl_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile:.
        /// </summary>
        internal static string Lbl_Mobile {
            get {
                return ResourceManager.GetString("Lbl_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr:.
        /// </summary>
        internal static string Lbl_Number {
            get {
                return ResourceManager.GetString("Lbl_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient:.
        /// </summary>
        internal static string Lbl_Patient {
            get {
                return ResourceManager.GetString("Lbl_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string Lbl_Phone {
            get {
                return ResourceManager.GetString("Lbl_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of birth:.
        /// </summary>
        internal static string Lbl_PlaceOfBirth {
            get {
                return ResourceManager.GetString("Lbl_PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code:.
        /// </summary>
        internal static string Lbl_PostalCode {
            get {
                return ResourceManager.GetString("Lbl_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession:.
        /// </summary>
        internal static string Lbl_Profession {
            get {
                return ResourceManager.GetString("Lbl_Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation:.
        /// </summary>
        internal static string Lbl_Reputation {
            get {
                return ResourceManager.GetString("Lbl_Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialisation:.
        /// </summary>
        internal static string Lbl_Specialisation {
            get {
                return ResourceManager.GetString("Lbl_Specialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        internal static string Lbl_Street {
            get {
                return ResourceManager.GetString("Lbl_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change picture....
        /// </summary>
        internal static string Link_ChangePicture {
            get {
                return ResourceManager.GetString("Link_ChangePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to select the doctor.
        /// </summary>
        internal static string Msg_DoubleClick {
            get {
                return ResourceManager.GetString("Msg_DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to unbind the doctor..
        /// </summary>
        internal static string Msg_DoubleClickToUnbind {
            get {
                return ResourceManager.GetString("Msg_DoubleClickToUnbind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to leave without saving?.
        /// </summary>
        internal static string Question_LeaveWithoutSaving {
            get {
                return ResourceManager.GetString("Question_LeaveWithoutSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a doctor....
        /// </summary>
        internal static string Title_AddDoctor {
            get {
                return ResourceManager.GetString("Title_AddDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an insurance....
        /// </summary>
        internal static string Title_AddInsurance {
            get {
                return ResourceManager.GetString("Title_AddInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a medical practice....
        /// </summary>
        internal static string Title_AddPractice {
            get {
                return ResourceManager.GetString("Title_AddPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a profession....
        /// </summary>
        internal static string Title_AddProfession {
            get {
                return ResourceManager.GetString("Title_AddProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add reputation....
        /// </summary>
        internal static string Title_AddReputation {
            get {
                return ResourceManager.GetString("Title_AddReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a specialisation....
        /// </summary>
        internal static string Title_AddSpecialisation {
            get {
                return ResourceManager.GetString("Title_AddSpecialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind a doctor....
        /// </summary>
        internal static string Title_BindDoctor {
            get {
                return ResourceManager.GetString("Title_BindDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient overview.
        /// </summary>
        internal static string Title_Page {
            get {
                return ResourceManager.GetString("Title_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient overview.
        /// </summary>
        internal static string Title_PluginName {
            get {
                return ResourceManager.GetString("Title_PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a doctor....
        /// </summary>
        internal static string Title_TitleWatermark {
            get {
                return ResourceManager.GetString("Title_TitleWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbind a doctor....
        /// </summary>
        internal static string Title_UnbindDoctor {
            get {
                return ResourceManager.GetString("Title_UnbindDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the modification done on the patient?.
        /// </summary>
        internal static string Warn_ImpossibleToDisplayThumb {
            get {
                return ResourceManager.GetString("Warn_ImpossibleToDisplayThumb", resourceCulture);
            }
        }
    }
}
