//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.DbConvert.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.DbConvert.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibla to map &apos;{0}&apos;.
        /// </summary>
        internal static string Error_ImpossibleToMap {
            get {
                return ResourceManager.GetString("Error_ImpossibleToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database selected.
        /// </summary>
        internal static string Log_DbChosen {
            get {
                return ResourceManager.GetString("Log_DbChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doctor(s) for the patient &apos;{1}&apos;.
        /// </summary>
        internal static string Log_DoctorCount {
            get {
                return ResourceManager.GetString("Log_DoctorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import succeeded!.
        /// </summary>
        internal static string Log_EndImporting {
            get {
                return ResourceManager.GetString("Log_EndImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected database is invalid.
        /// </summary>
        internal static string Log_InvalidDb {
            get {
                return ResourceManager.GetString("Log_InvalidDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item with id &apos;{0}&apos; was found.
        /// </summary>
        internal static string Log_NoItem {
            get {
                return ResourceManager.GetString("Log_NoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} patient(s) imported..
        /// </summary>
        internal static string Log_PatientCount {
            get {
                return ResourceManager.GetString("Log_PatientCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} élément(s) importé pour le patient &apos;{1}&apos;.
        /// </summary>
        internal static string Log_RecordCount {
            get {
                return ResourceManager.GetString("Log_RecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start importing....
        /// </summary>
        internal static string Log_StartImporting {
            get {
                return ResourceManager.GetString("Log_StartImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This was done by the nDoctor 3 import facility.
        /// </summary>
        internal static string Msg_DoneByConverter {
            get {
                return ResourceManager.GetString("Msg_DoneByConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patients are imported in the database..
        /// </summary>
        internal static string Msg_PatientsSaved {
            get {
                return ResourceManager.GetString("Msg_PatientsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB nDoctor 2.
        /// </summary>
        internal static string Title_ChoseOldDb {
            get {
                return ResourceManager.GetString("Title_ChoseOldDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data.
        /// </summary>
        internal static string Title_DbConvertManager {
            get {
                return ResourceManager.GetString("Title_DbConvertManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string Title_DefaultAppointementType {
            get {
                return ResourceManager.GetString("Title_DefaultAppointementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical pictures.
        /// </summary>
        internal static string Title_DefaultPictureType {
            get {
                return ResourceManager.GetString("Title_DefaultPictureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription.
        /// </summary>
        internal static string Title_DefaultPrescription {
            get {
                return ResourceManager.GetString("Title_DefaultPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Title_Import {
            get {
                return ResourceManager.GetString("Title_Import", resourceCulture);
            }
        }
    }
}
