//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.FamilyViewer.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.FamilyViewer.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlever ce patient de la famille.
        /// </summary>
        internal static string Menu_RemoveRelation {
            get {
                return ResourceManager.GetString("Menu_RemoveRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour le monde!.
        /// </summary>
        internal static string Msg_HelloWorld {
            get {
                return ResourceManager.GetString("Msg_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical record cabinet loaded.
        /// </summary>
        internal static string Msg_MedicalRecordLoaded {
            get {
                return ResourceManager.GetString("Msg_MedicalRecordLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the {0} of {1}.
        /// </summary>
        internal static string Msg_Relation {
            get {
                return ResourceManager.GetString("Msg_Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a relation.
        /// </summary>
        internal static string Title_AddRelation {
            get {
                return ResourceManager.GetString("Title_AddRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorisations.
        /// </summary>
        internal static string Title_AuthorisationManager {
            get {
                return ResourceManager.GetString("Title_AuthorisationManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string Title_FamilyManager {
            get {
                return ResourceManager.GetString("Title_FamilyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin&apos;s title.
        /// </summary>
        internal static string Title_Page {
            get {
                return ResourceManager.GetString("Title_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Title_SearchWatermark {
            get {
                return ResourceManager.GetString("Title_SearchWatermark", resourceCulture);
            }
        }
    }
}
