//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.BmiRecord.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.BmiRecord.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        internal static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bmi chart.
        /// </summary>
        internal static string Header_BmiChart {
            get {
                return ResourceManager.GetString("Header_BmiChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        internal static string Header_Chart {
            get {
                return ResourceManager.GetString("Header_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw data.
        /// </summary>
        internal static string Header_Data {
            get {
                return ResourceManager.GetString("Header_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Header_Date {
            get {
                return ResourceManager.GetString("Header_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height chart.
        /// </summary>
        internal static string Header_HeightChart {
            get {
                return ResourceManager.GetString("Header_HeightChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight chart.
        /// </summary>
        internal static string Header_WeightChart {
            get {
                return ResourceManager.GetString("Header_WeightChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous supprimer cet entrée?.
        /// </summary>
        internal static string Msg_AskDeleteBmi {
            get {
                return ResourceManager.GetString("Msg_AskDeleteBmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item added into BMI history.
        /// </summary>
        internal static string Msg_BmiAdded {
            get {
                return ResourceManager.GetString("Msg_BmiAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI entry deleted.
        /// </summary>
        internal static string Msg_BmiDeleted {
            get {
                return ResourceManager.GetString("Msg_BmiDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI history loaded.
        /// </summary>
        internal static string Msg_BmiHistoryLoaded {
            get {
                return ResourceManager.GetString("Msg_BmiHistoryLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while adding an item into the BMI history.
        /// </summary>
        internal static string Msg_ErrAddBmi {
            get {
                return ResourceManager.GetString("Msg_ErrAddBmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        internal static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue. Vérifiez les logs pour plus d&apos;informations.
        /// </summary>
        internal static string Msg_ErrorOccured {
            get {
                return ResourceManager.GetString("Msg_ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a BMI entry.
        /// </summary>
        internal static string Title_AddBmi {
            get {
                return ResourceManager.GetString("Title_AddBmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bmi.
        /// </summary>
        internal static string Title_Bmi {
            get {
                return ResourceManager.GetString("Title_Bmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Title_BmiDate {
            get {
                return ResourceManager.GetString("Title_BmiDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Title_BmiHeight {
            get {
                return ResourceManager.GetString("Title_BmiHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obesity.
        /// </summary>
        internal static string Title_BmiObesity {
            get {
                return ResourceManager.GetString("Title_BmiObesity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overweight.
        /// </summary>
        internal static string Title_BmiOverweight {
            get {
                return ResourceManager.GetString("Title_BmiOverweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        internal static string Title_BmiRecordManager {
            get {
                return ResourceManager.GetString("Title_BmiRecordManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underweight.
        /// </summary>
        internal static string Title_BmiUnderweight {
            get {
                return ResourceManager.GetString("Title_BmiUnderweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Title_BmiWeight {
            get {
                return ResourceManager.GetString("Title_BmiWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        internal static string Title_BmiXAxes {
            get {
                return ResourceManager.GetString("Title_BmiXAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI index.
        /// </summary>
        internal static string Title_BmiYAxes {
            get {
                return ResourceManager.GetString("Title_BmiYAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Title_BtnAdd {
            get {
                return ResourceManager.GetString("Title_BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Title_BtnDelete {
            get {
                return ResourceManager.GetString("Title_BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new bmi entry.
        /// </summary>
        internal static string Title_ExpanderHeaderAdd {
            get {
                return ResourceManager.GetString("Title_ExpanderHeaderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete BMI entry.
        /// </summary>
        internal static string Title_ExpanderHeaderDelete {
            get {
                return ResourceManager.GetString("Title_ExpanderHeaderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string Title_From {
            get {
                return ResourceManager.GetString("Title_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback the last deletion.
        /// </summary>
        internal static string Title_RollbackBmi {
            get {
                return ResourceManager.GetString("Title_RollbackBmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Title_To {
            get {
                return ResourceManager.GetString("Title_To", resourceCulture);
            }
        }
    }
}
