//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.PictureManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.PictureManager.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Header_Information {
            get {
                return ResourceManager.GetString("Header_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;All the pictures&gt;.
        /// </summary>
        internal static string Msg_AllTags {
            get {
                return ResourceManager.GetString("Msg_AllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occued while saving the picture.
        /// </summary>
        internal static string Msg_ErOnSavePicture {
            get {
                return ResourceManager.GetString("Msg_ErOnSavePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while refreshing the pictures.
        /// </summary>
        internal static string Msg_ErrorFailToRefreshPicture {
            get {
                return ResourceManager.GetString("Msg_ErrorFailToRefreshPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Check the logs for further information..
        /// </summary>
        internal static string Msg_ErrorOccured {
            get {
                return ResourceManager.GetString("Msg_ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading medical pictures. {0}.
        /// </summary>
        internal static string Msg_FailToLoadMedicalPictures {
            get {
                return ResourceManager.GetString("Msg_FailToLoadMedicalPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture added.
        /// </summary>
        internal static string Msg_PictureAdded {
            get {
                return ResourceManager.GetString("Msg_PictureAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture updated.
        /// </summary>
        internal static string Msg_PictureUpdated {
            get {
                return ResourceManager.GetString("Msg_PictureUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a category.
        /// </summary>
        internal static string Title_AddPicType {
            get {
                return ResourceManager.GetString("Title_AddPicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a picture.
        /// </summary>
        internal static string Title_BtnAddPic {
            get {
                return ResourceManager.GetString("Title_BtnAddPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Title_BtnSearch {
            get {
                return ResourceManager.GetString("Title_BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string Title_Category {
            get {
                return ResourceManager.GetString("Title_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date: {0}.
        /// </summary>
        internal static string Title_CreationDate {
            get {
                return ResourceManager.GetString("Title_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update: {0}.
        /// </summary>
        internal static string Title_LastUpdate {
            get {
                return ResourceManager.GetString("Title_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation succeeded..
        /// </summary>
        internal static string Title_OperationDone {
            get {
                return ResourceManager.GetString("Title_OperationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical pictures.
        /// </summary>
        internal static string Title_PictureManager {
            get {
                return ResourceManager.GetString("Title_PictureManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string Title_Pictures {
            get {
                return ResourceManager.GetString("Title_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Title_Save {
            get {
                return ResourceManager.GetString("Title_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Title_Search {
            get {
                return ResourceManager.GetString("Title_Search", resourceCulture);
            }
        }
    }
}
