//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.RescueTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.RescueTools.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate all.
        /// </summary>
        internal static string Btn_DeactivateAll {
            get {
                return ResourceManager.GetString("Btn_DeactivateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find doubloons....
        /// </summary>
        internal static string Btn_Refresh {
            get {
                return ResourceManager.GetString("Btn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string Btn_Replace {
            get {
                return ResourceManager.GetString("Btn_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with first doublon.
        /// </summary>
        internal static string Btn_ReplaceWithFirst {
            get {
                return ResourceManager.GetString("Btn_ReplaceWithFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on age.
        /// </summary>
        internal static string Db_SearchOnAge {
            get {
                return ResourceManager.GetString("Db_SearchOnAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Dgv_Age {
            get {
                return ResourceManager.GetString("Dgv_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string Dgv_Birthdate {
            get {
                return ResourceManager.GetString("Dgv_Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated?.
        /// </summary>
        internal static string Dgv_Deactivated {
            get {
                return ResourceManager.GetString("Dgv_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string Dgv_FirstName {
            get {
                return ResourceManager.GetString("Dgv_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Dgv_LastName {
            get {
                return ResourceManager.GetString("Dgv_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Gb_Address {
            get {
                return ResourceManager.GetString("Gb_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Gb_Details {
            get {
                return ResourceManager.GetString("Gb_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubloons.
        /// </summary>
        internal static string Gb_Doubloons {
            get {
                return ResourceManager.GetString("Gb_Doubloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kept doctor.
        /// </summary>
        internal static string Gb_KeptDoctor {
            get {
                return ResourceManager.GetString("Gb_KeptDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesionnal contact.
        /// </summary>
        internal static string Gb_ProContact {
            get {
                return ResourceManager.GetString("Gb_ProContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Lbl_Mail {
            get {
                return ResourceManager.GetString("Lbl_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Lbl_Mobile {
            get {
                return ResourceManager.GetString("Lbl_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Lbl_Phone {
            get {
                return ResourceManager.GetString("Lbl_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace doubloons with this doctor? If you click on &quot;Yes&quot;, you&apos;ll replace all the other doubloons with this doctor and delete all the doubloons from the database. This action can&apos;t be undone..
        /// </summary>
        internal static string Msg_ConfirmReplacement {
            get {
                return ResourceManager.GetString("Msg_ConfirmReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes sur le point de remplacer TOUS les médecins avec le même nom, prénom et spécialisation avec le premier doublon trouvé. N&apos;appliquez cette commande que si vous êtes certains que tous les médecins doublons contiennent les même données! Voulez-vous procéder?.
        /// </summary>
        internal static string Msg_ConfirmReplaceWithFirst {
            get {
                return ResourceManager.GetString("Msg_ConfirmReplaceWithFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubloons: {0}.
        /// </summary>
        internal static string Msg_DoubloonsCount {
            get {
                return ResourceManager.GetString("Msg_DoubloonsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubloons has been deleted.
        /// </summary>
        internal static string Msg_DoubloonsDeleted {
            get {
                return ResourceManager.GetString("Msg_DoubloonsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doublon(s) trouvé(s).
        /// </summary>
        internal static string Msg_DoubloonsFound {
            get {
                return ResourceManager.GetString("Msg_DoubloonsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient updated.
        /// </summary>
        internal static string Msg_PatientUpdated {
            get {
                return ResourceManager.GetString("Msg_PatientUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking on &quot;Replace&quot;, you will remove all doubloons and replace them with this doctor. This action cannot be cancelled!.
        /// </summary>
        internal static string Msg_ReplaceDoctorExplanations {
            get {
                return ResourceManager.GetString("Msg_ReplaceDoctorExplanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients too old.
        /// </summary>
        internal static string Tab_Age {
            get {
                return ResourceManager.GetString("Tab_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubloons doctors.
        /// </summary>
        internal static string Tab_DoctorDoubloons {
            get {
                return ResourceManager.GetString("Tab_DoctorDoubloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database management.
        /// </summary>
        internal static string Title_FirstAidManager {
            get {
                return ResourceManager.GetString("Title_FirstAidManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database management.
        /// </summary>
        internal static string Title_Page {
            get {
                return ResourceManager.GetString("Title_Page", resourceCulture);
            }
        }
    }
}
