//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.FamilyManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.FamilyManager.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s medical record.
        /// </summary>
        internal static string Btn_Father {
            get {
                return ResourceManager.GetString("Btn_Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s medical record.
        /// </summary>
        internal static string Btn_Mother {
            get {
                return ResourceManager.GetString("Btn_Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Btn_Remove {
            get {
                return ResourceManager.GetString("Btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add this family member.
        /// </summary>
        internal static string Msg_AskAddMember {
            get {
                return ResourceManager.GetString("Msg_AskAddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove this family member?.
        /// </summary>
        internal static string Msg_AskRemoveMember {
            get {
                return ResourceManager.GetString("Msg_AskRemoveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when loading the family manager..
        /// </summary>
        internal static string Msg_FailToLoadFamilyManager {
            get {
                return ResourceManager.GetString("Msg_FailToLoadFamilyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family updated.
        /// </summary>
        internal static string Msg_FamilySaved {
            get {
                return ResourceManager.GetString("Msg_FamilySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the {0} of {1}.
        /// </summary>
        internal static string Msg_Relation {
            get {
                return ResourceManager.GetString("Msg_Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family member added.
        /// </summary>
        internal static string Msg_RelationAdded {
            get {
                return ResourceManager.GetString("Msg_RelationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family member deleted.
        /// </summary>
        internal static string Msg_RelationRemoved {
            get {
                return ResourceManager.GetString("Msg_RelationRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left to right.
        /// </summary>
        internal static string RelationTypeDirection_LeftToRight {
            get {
                return ResourceManager.GetString("RelationTypeDirection_LeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to left.
        /// </summary>
        internal static string RelationTypeDirection_RightToLeft {
            get {
                return ResourceManager.GetString("RelationTypeDirection_RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage family members.
        /// </summary>
        internal static string Title_AccodrionManage {
            get {
                return ResourceManager.GetString("Title_AccodrionManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string Title_AccordionData {
            get {
                return ResourceManager.GetString("Title_AccordionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add family members.
        /// </summary>
        internal static string Title_AddFamilyManager {
            get {
                return ResourceManager.GetString("Title_AddFamilyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add relation.
        /// </summary>
        internal static string Title_AddRelation {
            get {
                return ResourceManager.GetString("Title_AddRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string Title_FamilyManager {
            get {
                return ResourceManager.GetString("Title_FamilyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove family members.
        /// </summary>
        internal static string Title_RemoveFamilyManager {
            get {
                return ResourceManager.GetString("Title_RemoveFamilyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Title_Save {
            get {
                return ResourceManager.GetString("Title_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First or last name.
        /// </summary>
        internal static string Title_SearchWatermark {
            get {
                return ResourceManager.GetString("Title_SearchWatermark", resourceCulture);
            }
        }
    }
}
