//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.NDoctor.Plugins.Authorisation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.NDoctor.Plugins.Authorisation.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer.
        /// </summary>
        internal static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this task.
        /// </summary>
        internal static string Btn_RemoveTask {
            get {
                return ResourceManager.GetString("Btn_RemoveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string Btn_Validate {
            get {
                return ResourceManager.GetString("Btn_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is selected.
        /// </summary>
        internal static string Grid_TaskIsSelected {
            get {
                return ResourceManager.GetString("Grid_TaskIsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Grid_TaskName {
            get {
                return ResourceManager.GetString("Grid_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned role.
        /// </summary>
        internal static string Header_AssignedRole {
            get {
                return ResourceManager.GetString("Header_AssignedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par défaut.
        /// </summary>
        internal static string Header_IsDefault {
            get {
                return ResourceManager.GetString("Header_IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Header_Name {
            get {
                return ResourceManager.GetString("Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available tasks:.
        /// </summary>
        internal static string Lbl_AvailableTasks {
            get {
                return ResourceManager.GetString("Lbl_AvailableTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Lbl_RoleDescription {
            get {
                return ResourceManager.GetString("Lbl_RoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role&apos;s name:.
        /// </summary>
        internal static string Lbl_RoleName {
            get {
                return ResourceManager.GetString("Lbl_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles:.
        /// </summary>
        internal static string Lbl_Roles {
            get {
                return ResourceManager.GetString("Lbl_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Menu_Navigation {
            get {
                return ResourceManager.GetString("Menu_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Menu_Remove {
            get {
                return ResourceManager.GetString("Menu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role is assigned to, at least, one user. Unassigned this role from all these user before removing this one..
        /// </summary>
        internal static string Msg_CantRemoveRole {
            get {
                return ResourceManager.GetString("Msg_CantRemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world!.
        /// </summary>
        internal static string Msg_HelloWorld {
            get {
                return ResourceManager.GetString("Msg_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role created.
        /// </summary>
        internal static string Msg_RoleCreated {
            get {
                return ResourceManager.GetString("Msg_RoleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned role changed for {0}.
        /// </summary>
        internal static string Msg_RoleUpdatedFor {
            get {
                return ResourceManager.GetString("Msg_RoleUpdatedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task created.
        /// </summary>
        internal static string Msg_TaskCreated {
            get {
                return ResourceManager.GetString("Msg_TaskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task removed.
        /// </summary>
        internal static string Msg_TaskRemoved {
            get {
                return ResourceManager.GetString("Msg_TaskRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the role.
        /// </summary>
        internal static string Msg_UpdateRole {
            get {
                return ResourceManager.GetString("Msg_UpdateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous supprimer ce rôle?.
        /// </summary>
        internal static string Question_DeleteRole {
            get {
                return ResourceManager.GetString("Question_DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a role.
        /// </summary>
        internal static string Title_AddRole {
            get {
                return ResourceManager.GetString("Title_AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorisations.
        /// </summary>
        internal static string Title_AuthorisationManager {
            get {
                return ResourceManager.GetString("Title_AuthorisationManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les rôles.
        /// </summary>
        internal static string Title_Manage {
            get {
                return ResourceManager.GetString("Title_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin&apos;s title.
        /// </summary>
        internal static string Title_Page {
            get {
                return ResourceManager.GetString("Title_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage roles.
        /// </summary>
        internal static string Title_RoleManager {
            get {
                return ResourceManager.GetString("Title_RoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manages users.
        /// </summary>
        internal static string Title_UserManager {
            get {
                return ResourceManager.GetString("Title_UserManager", resourceCulture);
            }
        }
    }
}
